name: Semantic Pull Request

on:
  workflow_call:
    inputs:
      types:
        required: false
        type: string
        default: |
          ci
          composer
          docs
          fix
          security
          feat
          perf
          refactor
          chore
      scopes:
        required: false
        type: string
        default: |
          application
          deps
          domain
          infrastructure
          kernel
          shared
          support
          tests
          other
      requireScope:
        required: false
        type: boolean
        default: true
    secrets:
      GH_TOKEN:
        required: true

jobs:
  main:
    name: Validate PR title
    runs-on: ubuntu-latest
    steps:
      - uses: amannn/action-semantic-pull-request@v6
        with:
          types: ${{ inputs.types }}
          scopes: ${{ inputs.scopes }}
          requireScope: ${{ inputs.requireScope }}
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}