name: Semantic Pull Request

on:
  workflow_call:
    secrets:
      GH_TOKEN:
        required: true

jobs:
  main:
    name: Validate PR title
    runs-on: ubuntu-latest
    steps:
      - uses: amannn/action-semantic-pull-request@v6
        with:
          types: |
            ci
            composer
            docs
            fix
            security
            feat
            perf
            refactor
            chore
          scopes: |
            application
            deps
            domain
            infrastructure
            kernel
            shared
            support
            tests
            other
          requireScope: true
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}